load("interimData/completeMotifFamilyTable.RData")
library(multicore)
library(ggplot2)
library(data.table)
source("Code/makeFigures/helperFunctionsFinal.R")
source("Code/makeFigures/prepareRankingTables_fun.R")

load("interimData/allResH3K4.RDat")
load("interimData/bothMatDirectsH3K4out.RDat")
alldf1=makeDF(bothMats,allResH3K4,motifFamilyTable)
save(alldf1,file="interimData/alldf1H3K4.RDat")

load("interimData/allResH3K4_uncor.RDat")
load("interimData/bothMatDirectsH3K4out.RDat")
alldf1=makeDF(bothMats,allResH3K4_uncor,motifFamilyTable)
save(alldf1,file="interimData/alldf1H3K4_uncor.RDat")

load("interimData/allResH3K4Rev.RDat")
load("interimData/bothMatDirectsH3K4out.RDat")
alldf1=makeDF(bothMats,allResH3K4Rev,motifFamilyTable)
save(alldf1,file="interimData/alldf1H3K4_rev.RDat")
