
load("interimData/allResMinus.RDat")
load("interimData/bothMatDirectsDeterministicPCMotif0PCsRemoved.RDat")
alldfMinus=makeDF(bothMats,allResMinus,motifFamilyTable)
save(alldfMinus,file="interimData/alldfMinus.RDat")
load("interimData/allRes0.RDat")
load("interimData/bothMatDirectsDeterministicPCMotif0PCsRemoved.RDat")
alldf0=makeDF(bothMats,allRes0,motifFamilyTable)
save(alldf0,file="interimData/alldf0.RDat")
load("interimData/allRes1.RDat")
load("interimData/bothMatDirectsDeterministicPCMotif1PCsRemoved.RDat")
alldf1=makeDF(bothMats,allRes1,motifFamilyTable)
save(alldf1,file="interimData/alldf1.RDat")

load("interimData/allRes1TopRemoved.RDat")
load("interimData/alldf1.RDat")
names(allRes1TopRemoved)=alldf1[geneNr=="first",motifName]
alldf1TopRemoved=makeDFTopRemoved(allRes1TopRemoved,motifFamilyTable)
save(alldf1TopRemoved,file="interimData/alldf1TopRemoved.RDat")
load("interimData/allRes1TopRemovedShuffled.RDat")
load("interimData/alldf1.RDat")
names(allRes1TopRemovedShuffled)=alldf1[geneNr=="first",motifName]
alldf1TopRemovedShuffled=makeDFTopRemoved(allRes1TopRemovedShuffled,motifFamilyTable)
save(alldf1TopRemovedShuffled,file="interimData/alldf1TopRemovedShuffled.RDat")

load("interimData/allRes1.RDat")
load("interimData/bothMatDirectsDeterministicPCMotif1PCsRemoved.RDat")
alldf1=makeDF(bothMats,allRes1,motifFamilyTable)
allResTopIgnored=removeTopGenesFromAllRes(allRes1,motifFamilyTable)
save(allResTopIgnored,file="interimData/allResTopIgnored.RDat")
alldf1TopIgnored=makeDF(bothMats,allResTopIgnored,motifFamilyTable)
save(alldf1TopIgnored,file="interimData/alldf1TopIgnored.RDat")

load("interimData/allRes1Roadmap.RDat")
load("interimData/bothMatDirectsDeterministicPCMotif1PCsRemovedRoadmap.RDat")
alldf1=makeDF(bothMats,allRes1,motifFamilyTable)
save(alldf1,file="interimData/alldfRoadmap.RDat")
