library(svglite)
library(ggplot2)
library(data.table)
library(reshape2)
load("interimData/bothMatDirectsDeterministicPCMotif1PCsRemoved.RDat")
AA0=cor(bothMats[[1]])
AA=melt(AA0^2)
svglite("PaperDocs/Images/cor2Motif1.svg")
p1=ggplot(AA, aes(Var1, Var2)) + geom_tile(aes(fill = value)) + scale_fill_gradient(low = "white",high = "red")+theme(axis.text=element_text(size=1))
plot(p1)
dev.off()

BB0=cor(bothMats[[2]])
BB=melt(BB0^2)
svglite("PaperDocs/Images/cor2Expr.svg")
p2=ggplot(BB, aes(Var1, Var2)) + geom_tile(aes(fill = value)) + scale_fill_gradient(low = "white",high = "red")+theme(axis.text=element_text(size=1))
plot(p2)
dev.off()

load("interimData/bothMatDirectsDeterministicPCMotif0PCsRemoved.RDat")
CC0=cor(bothMats[[1]])
CC=melt(CC0^2)
svglite("PaperDocs/Images/cor2Motif0.svg")
p3=ggplot(CC, aes(Var1, Var2)) + geom_tile(aes(fill = value)) + scale_fill_gradient(low = "white",high = "red")+theme(axis.text=element_text(size=1))
plot(p3)
dev.off()
len=length(AA0[,1])
e1=data.frame(eigenvalue=eigen(AA0)$values, type="Motif 1 PC removed",index = c(1:len))
e2=data.frame(eigenvalue=eigen(BB0)$values, type="Expression",index = c(1:len))
e3=data.frame(eigenvalue=eigen(CC0)$values, type="Motif",index = c(1:len))
e4=data.table(rbind(rbind(e1,e2),e3))
svglite("PaperDocs/Images/eigenValues.svg",width=10,height=10)
p=ggplot(data=e4,aes(y=eigenvalue,x=index, group=type,fill=type,colour=type))+ geom_point(size=8)+xlim(c(0,25))+theme_classic()+theme(axis.text=element_text(size=32),axis.title=element_text(size=32), legend.text=element_text(size=32),legend.justification=c(0,0), legend.position=c(0.4,0.4),legend.title=element_blank())
plot(p)
dev.off()